// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Migrations exigem uma conexão persistente. Em produção, a aplicação usa
    // DATABASE_URL via Transaction Pooler, enquanto o Prisma CLI prioriza a
    // DIRECT_URL (Session Pooler/conexão direta) para evitar travamentos.
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
